// Generated by CoffeeScript 1.7.1
(function() {
  var Player;

  Player = (function() {
    function Player(name, computer) {
      this.name = name;
      this.computer = computer;
      this.currency = 0;
      this.units = [];
    }

    return Player;

  })();

}).call(this);
